import { defineConfig } from 'orval'

const workspace = 'src/http/generated'

export default defineConfig({
  api: {
    input: {
      target:
        process.env.NEXT_PUBLIC_BACKEND_PUBLIC_API_BASE_URL ??
        'http://localhost:3333/docs-json',
    },
    output: {
      client: 'fetch',
      mode: 'tags-split',
      indexFiles: true,

      clean: true,
      prettier: true,

      workspace,
      target: 'api/api.ts',
      schemas: 'models',

      override: {
        useDates: true,
        useBigInt: true,
        useNamedParameters: true,

        fetch: {
          includeHttpResponseReturnType: false,
        },

        mutator: {
          name: 'http',
          path: './mutator/orval-mutator.ts',
        },

        header: (info) => [
          `Generated by Orval`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: [
        'pnpm exec ts-node ./scripts/fix-orval-barrels.ts',
        'pnpm exec prettier --write src/http/generated',
        'pnpm exec eslint --fix src/http/generated',
      ],
    },
  },
})
